### ISSUE TITLE
Default to $SOPS_AGE_KEY

### ISSUE THREAD

**Issue by tarasglek** [humphd/sops-age#5]
Atm one has to fetch the env var explicitly in code and pass it to decrypt.

decrypt(sops: SOPS, secretKey: string, keyPath?: string) 

Would also be nicer if decrypt signature was

decrypt(sops: SOPS, options? = {various ways to specify key go here})

**Comment by humphd** [comment]
Yeah, this seems like a good idea.  Could look for it env, look in `options`, etc.
